all:
	python train.py

build:
	python build_dataset.py;
	python train.py;

buildn:
	# python build_dataset.py 1;
	# python train.py;
	python build_dataset.py 2;
	python train.py;
	python build_dataset.py 3;
	python train.py;
	python build_dataset.py 4;
	python train.py;
	python build_dataset.py 5;
	python train.py;
	python build_dataset.py 6;
	python train.py;
	python build_dataset.py 7;
	python train.py;
	python build_dataset.py 8;
	python train.py;
	python build_dataset.py 9;
	python train.py;
	python build_dataset.py 10;
	python train.py;
	python build_dataset.py 11;
	python train.py;
	python build_dataset.py 12;
	python train.py;
	python build_dataset.py 13;
	python train.py;
	python build_dataset.py 14;
	python train.py;
	python build_dataset.py 15;
	python train.py;
	python build_dataset.py 16;
	python train.py;